version: '3'

services:
  dark-crystal:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: npm start
    ports:
      - "8990:3000"
    environment:
      - NODE_ENV=production
      - HOST=api.darkcrystal.pw
      - PORT=3000
